source 'git@github.com:CocoaPods/Specs.git' 
platform :ios, '8.0' 

target 'ios' do
    pod 'WeexSDK', '0.15.1'
    pod 'SDWebImage', '4.1.0'
    pod 'SocketRocket', '0.5.1'
    pod 'lottie-ios', '2.1.3'
    pod 'RTRootNavigationController', '~> 0.6.3'
end
