source 'git@github.com:CocoaPods/Specs.git' 
platform :ios, '8.0'

target 'ios' do
    pod 'WeexSDK', '0.17.0'
    pod 'SDWebImage', '4.1.0'
    pod 'SocketRocket', '0.5.1'
    pod 'lottie-ios', '2.1.5'
    pod 'RTRootNavigationController', '~> 0.6.3'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'PureLayout', '~> 3.0.2'
    pod 'TZImagePickerController', '~> 1.9.8'
    pod 'WechatOpenSDK', '~> 1.8.1'
    pod 'Charts', '~> 3.0.4'
    use_frameworks!
    pod 'UMCCommon'
    pod 'UMCAnalytics'
end
